apiVersion: v1
kind: Pod
metadata:
  name: pg-migration
spec:
  containers:
  - name: webapp-cve-processor
    image: maheshpoojaryneu/csye7125:webapp-cve-processor
    imagePullPolicy: Always

  initContainers:
  - name: flyway-init
    image: maheshpoojaryneu/csye7125:pg-migration-final
    imagePullPolicy: Always
    command:
    - "/bin/sh"
    - "-c"
    - "flyway -user={{ .Values.postgres.user }} -password={{ .Values.postgres.password }} -url=jdbc:postgresql://host.docker.internal:5432/cve migrate"
  imagePullSecrets:
  - name: {{ .Values.imagePullSecrets.name }}
  # hostAliases:
  # - ip: {{ .Values.ip }}
  #   # "172.17.0.1"  # Replace with the IP of host-gateway
  #   hostnames:
  #   - {{ .Values.hostname | quote }}
